version: '3'

services: 

  app:    
    build: 
      context: ./app
    image: node:15.8.0
    container_name: app 
    entrypoint: dockerize -wait tcp://db:27017 -timeout 20s docker-entrypoint.sh
    command: yarn start
    networks: 
      - node-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db
        
  db:
    image: mongo
    command: --serviceExecutor adaptive
    container_name: db
    restart: always
    tty: true
    environment: 
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - "27017:27017"
    networks: 
      - node-network    

networks: 
  node-network: 
    driver: bridge
  